#!/bin/sh

randdevice=/dev/hwrng

case $1 in 
	
	--check)
		if ! [ -e "$randdevice" ] ; then
			echo "$randdevice not found"
			exit 1
		fi
		if ! [ -x /bin/dd ] ; then
			echo "dd not found"
			exit 1
		fi
		exit 0
		
		;;
		
	--config)
		exit
		;;
		
	--priority)
		echo 10
		exit
		;;
		
	--get) 
		[ -n "$2" ] || exit 1
		dd if="$randdevice" bs=1M count=$2
		sleep 5
		exit
		;;
		
	*) echo "Usage < --check | --config | --get <megabytes> >"
		exit
		;;
		
esac	
