#!/bin/sh

# chkconfig 2345 10 90
# description: Start random data collecting daemon

### BEGIN INIT INFO
# Provides: 	     randomhelper
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start random data collecting daemon
### END INIT INFO
#
# make modules

# random-collector *should* under its user privlges
# but you can set this to root, if you so desire (security risk)
RANDUSER=randomhelper

PREFIXPATH=/usr/local

PATH=/bin:/sbin:/usr/bin:/usr/sbin:$PREFIXPATH/bin:$PREFIXPATH/sbin

DESC=randomhelper

# Source function library.
if [ -f /lib/lsb/init-functions ] ; then
  . /lib/lsb/init-functions
fi
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
fi

#test $DEBIAN_SCRIPT_DEBUG && set -v -x

# limit memory usage (careful with this)
#ulimit -s 128

start_rand() {
	
	if [ -n "$(pgrep -f "perl $PREFIXPATH/sbin/random-add")" ] \
	 || [ -n "$(pgrep -f "perl $PREFIXPATH/sbin/random-collector")" ] ; then
	 
	  echo "Random get and/or collector already running"
	  
	else
	  
	  # random add
	   su - -c "perl $PREFIXPATH/sbin/random-add > /dev/null 2>&1 &" > /dev/null 2>&1 &
	  
	  # random collector
	  if [ -n "$RANDUSER" ] ; then
	    
	    # user
	    mkdir -p /var/lib/randomhelper
	    chown "$RANDUSER:$RANDUSER" -R /var/lib/randomhelper
	    su - "$RANDUSER" -c "perl $PREFIXPATH/sbin/random-collector > /dev/null 2>&1 &" > /dev/null 2>&1 &
	    
	  else
	    
	    # root
	    su - -c "perl $PREFIXPATH/sbin/random-collector &" >/dev/null 2>&1 &
	    
	  fi
	  
	fi
	
}

stop_rand() {
	
	if [ -n "$(pgrep -f 'random-add')" ] ; then
	  kill $(pgrep -f "perl $PREFIXPATH/sbin/random-add")
	fi
	if [ -n "$(pgrep -f 'random-collector')" ] ; then
	  kill $(pgrep -f "perl $PREFIXPATH/sbin/random-collector")
	fi
	
}

status_rand() {
	RETVAL=0
	if [ -n "$(pgrep -f "perl $PREFIXPATH/sbin/random-add")" ] ; then
  	  [ -z "$1" ] && echo "Random-add running"
  	  RETVAL=1
  	else
  	  [ -z "$1" ] && echo "Random-add stopped"
  	fi
	if [ -n "$(pgrep -f "perl $PREFIXPATH/sbin/random-collector")" ] ; then
	  [ -z "$1" ] && echo "Random-collector running"
	  RETVAL=1
	else
	  [ -z "$1" ] && echo "Random-collector stopped"
	fi
	return
}

case "$1" in
  start)
	echo -n "Starting $DESC ... "
	
	start_rand
	
	sleep 3
	status_rand quiet
	if [ $RETVAL = 1 ] ; then
	  echo " OK"
	else
	  echo " FAILED"
	fi
	
    ;;
  stop)
	echo -n "Stopping $DESC ... "
	
	stop_rand
	
	sleep 3
	status_rand quiet
	if [ $RETVAL = 0 ] ; then
	  echo " OK"
	else
	  echo " FAILED"
	fi
	
    ;;
  restart|force-reload)
	echo -n "Restarting $DESC"
	stop_rand
	sleep 2
	start_rand
	echo " OK"
	
    ;;
  
  condrestart)
	status_rand quiet
	[ $RETVAL = 0 ] && exit
	echo -n "Restarting $DESC"
	stop_rand
	sleep 2
	start_rand
	echo " OK"
	
    ;;
  
  status)
  	status_rand
    ;;
  *)
	N=/etc/init.d/module-config
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload|status|cond-restart}" >&2
	exit 1
	;;
esac

exit 0
